SELECT * FROM COUNTRIES;
select * from DEPARTMENTS;
select * from  EMPLOYEES;
select * from EMPLOYEES;
select FIRST_NAME from EMPLOYEES;
select CITY from LOCATIONS;
select FIRST_NAME, LAST_NAME, SALARY from EMPLOYEES;
select STREET_ADDRESS, POSTAL_CODE from  LOCATIONS;
select distinct FIRST_NAME from EMPLOYEES;

select FIRST_NAME, LAST_NAME, PHONE_NUMBER from EMPLOYEES
where FIRST_NAME = 'David' and LAST_NAME = 'Lee';

select * from EMPLOYEES where SALARY > 7000;

select EMAIL from EMPLOYEES where SALARY <4000;

select * from  EMPLOYEES WHERE JOB_ID = 'IT_PROG' OR JOB_ID= 'SA_REP';

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY >= 5000 AND SALARY <= 10000;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 10000;









