SELECT * FROM COUNTRIES;
select * from DEPARTMENTS;
select * from  EMPLOYEES;
select * from EMPLOYEES;
select FIRST_NAME from EMPLOYEES;
select CITY from LOCATIONS;
select FIRST_NAME, LAST_NAME, SALARY from EMPLOYEES;
select STREET_ADDRESS, POSTAL_CODE from  LOCATIONS;
select distinct FIRST_NAME from EMPLOYEES;

select FIRST_NAME, LAST_NAME, PHONE_NUMBER from EMPLOYEES
where FIRST_NAME = 'David' and LAST_NAME = 'Lee';

select * from EMPLOYEES where SALARY > 7000;

select EMAIL from EMPLOYEES where SALARY <4000;

select * from  EMPLOYEES WHERE JOB_ID = 'IT_PROG' OR JOB_ID= 'SA_REP';

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY >= 5000 AND SALARY <= 10000;

SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 10000;

select  * from EMPLOYEES where EMPLOYEE_ID between 130 and 170;

select * from EMPLOYEES where EMPLOYEE_ID = 135 or EMPLOYEE_ID = 176 or EMPLOYEE_ID = 154 or
                              EMPLOYEE_ID = 129;

select *
from EMPLOYEES
where EMPLOYEE_ID in(135, 176,154,129); -- all info of employee with id 135,176,154,129

--get me city where country_id IT,US,UK

SELECT CITY FROM LOCATIONS WHERE COUNTRY_ID IN ('US', 'UK', 'IT');
















